name: Deploy
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repository"
        uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Python Dependencies Install
        run: pip install -r requirements.txt
      - name: Run script
        run: python -m stigaview_static -o out products
      - name: Copy Static Assets
        run: cp --verbose -r static/ out/static
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'stigaview-static'
          directory: 'out'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.repository == 'Mab879/stigaview-static' && github.ref == 'refs/heads/master'}}
