name: Deploy
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PAGES_DIR: out
    steps:
      - name: "Check out the repository"
        uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Python Dependencies Install
        run: pip install -r requirements.txt
      - name: Run script
        run: python -m stigaview_static -o  ${{ env.PAGES_DIR }} products
      - name: Copy Static Assets
        run: cp --verbose -r public_html/* ${{ env.PAGES_DIR }}/
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: master
          folder: ${{ env.PAGES_DIR }}
          repository-name: stigaview/stigaview.github.io
          single-commit: true
          token: ${{ secrets.STIGAVIEW_PAGES_TOKEN }}
          git-config-name: stigaview-publisher
          git-config-email: stigaview_ci@stigaview.com
        if: ${{ github.repository == 'Mab879/stigaview-static' && github.ref == 'refs/heads/master' }}
