name: Gate
on:
  push:
    branches: [ 'master', ]
  pull_request:
    branches: [ 'master', ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.11', ]
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repository"
        uses: actions/checkout@v3
      - name: "Install poetry"
        run: pipx install poetry
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Poetry Install
        run: poetry install
      - name: Run script
        run: poetry run python -m stigaview_static -o out stigs
